# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  access_key_id: AKIAI5KSWK7IG7AFALKA
  secret_access_key: des7odLs6eHnpBt03vNDYP3rRFKiiUpf5Og+cr22r
  backup_bucket_name: easygrouper.backups.itcadre.com

test:
  access_key_id: AKIAI5KSWK7IG7AFALKA
  secret_access_key: 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
  backup_bucket_name: easygrouper.backups.itcadre.com

production:
  access_key_id: AKIAI5KSWK7IG7AFALKA
  secret_access_key: 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
  backup_bucket_name: easygrouper.backups.itcadre.com

-# end of file
