# S3 creds
development:
  access_key_id: AKIAI5KSWK7IG7AFALKA
  secret_access_key: des7odLs6eHnpBt03vNDYP3rRFKiiUpf5Og+cr22r
  backup_bucket_name: easygrouper.backups.itcadre.com
  heroku_app_name: itcdevtest

test:
  access_key_id: AKIAI5KSWK7IG7AFALKA
  secret_access_key: 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
  backup_bucket_name: easygrouper.backups.itcadre.com
  heroku_app_name: itcdevtest

production:
  access_key_id: AKIAI5KSWK7IG7AFALKA
  secret_access_key: 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
  backup_bucket_name: easygrouper.backups.itcadre.com
  heroku_app_name: itcdevtest
  
# end of file
