development:
  adapter: postgresql
  encoding: unicode
  database: itcdevtest
  pool: 5
  port: 5432
  username: dtweb
  password: dtweb
  
test:
  adapter: postgresql
  encoding: unicode
  database: test_itcdevtest
  pool: 5
  port: 5432
  username: postgres
  password: postgres
  min_messages: WARNING

production:
    adapter: postgresql
    encoding: unicode
    database: itcdevtest_production
    pool: 5
    port: 5432
    username: dtweb
    password: dtweb